### PR TITLE
Added functionality to create a note for each mount

### PR DESCRIPTION
**Pull request by finnlux**
Functionality requested by a streamer. Thought it would be a good feature request for me to branch into LUA with.

### CODE REVIEW

**Comment by exochron** [comment]
Hey, thank you for this Pull Request. You are actually the first one, who adds a whole new feature here. 👍 
I'm going to add this into the next version after cleaning and testing it a bit. 😃

Also, I'm a bit curious about that streamer. Do you have a link of her/him?

**Comment by finnlux** [comment]
Sweet. Let me know what sorts of things you clean up. I think it all works but there are probably things I've done "incorrect" because of not fully understanding LUA scoping or capabilities.

The streamer is TouchpadWarrior. He streams almost every night at 11pm CST. He has 879 mounts. 
https://www.twitch.tv/touchpadwarrior

**Comment by exochron** [comment]
now worries. scoping is the first hurdle to overcome as aspiring addon developer. 😉
by default all variables or functions are public/global. that means every other addon could access or overwrite them. (Similar to JavaScript with all variables within a document.) So it's just good practice to keep the public clutter as minimal as possible to avoid naming collisions with other addons.

**Comment by exochron** [comment]
okay, so far so good.  :) 
I've moved some stuff around. For instance the note is displayed within the gametoolip of mounts instead of an extra tooltip. (I'd like to keep the UI style close to the original mount journal.)  The note is also displayed underneath the lore text.
You can check it out in branch [2.19](https://github.com/exochron/MountJournalEnhanced/tree/2.19).

**Comment by finnlux** [comment]
Oh I see you got rid of the tooltip altogether. Yeah I struggled on finding the right frame/window to make for the dialog and the tooltip both but what you did makes sense. I see I also missed a localization. Thanks for cleaning it up!

**Pull request merged**
